#!/bin/bash

# Copyright 2022-2025 The nagare media authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -o pipefail

TASK="$1"
ROOT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
TASKS_DIR="${ROOT_DIR}/scripts/tasks"

log()   { >&2 echo "=> $*"; }
warn()  { log "warning: $*"; }
fatal() { log "fatal: $*"; exit 1; }

log "${TASK} start"
cd "${ROOT_DIR}"
. "${TASKS_DIR}/${TASK}"
log "${TASK} end"
