#!/bin/bash

# Copyright 2022-2025 The nagare media authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Main

INGEST_HOST=${INGEST_HOST:-localhost:8080}

ffmpeg -hide_banner \
  -re -f lavfi -i "
    testsrc2=size=1280x720:rate=25,
    drawbox=x=0:y=0:w=700:h=50:c=black@.6:t=fill,
    drawtext=x=  5:y=5:fontsize=54:fontcolor=white:text='%{pts\:gmtime\:$(date +%s)\:%Y-%m-%d}',
    drawtext=x=345:y=5:fontsize=54:fontcolor=white:timecode='$(date -u '+%H\:%M\:%S')\:00':rate=25:tc24hmax=1,
    setparams=field_mode=prog:range=tv:color_primaries=bt709:color_trc=bt709:colorspace=bt709,
    format=yuv420p" \
  -re -f lavfi -i "
    sine=f=1000:r=48000:samples_per_frame='st(0,mod(n,5)); 1602-not(not(eq(ld(0),1)+eq(ld(0),3)))'" \
  -shortest \
  -fflags genpts \
  \
  -filter_complex "
    [0:v]drawtext=x=(w-text_w)-5:y=5:fontsize=54:fontcolor=white:text='720p':box=1:boxcolor=black@.6:boxborderw=5[v720p];
    [0:v]drawtext=x=(w-text_w)-5:y=5:fontsize=54:fontcolor=white:text='360p':box=1:boxcolor=black@.6:boxborderw=5,scale=640x360[v360p]
  " \
  \
  -map [v720p] \
  -c:v libx264 \
    -preset:v veryfast \
    -tune zerolatency \
    -profile:v main \
    -crf:v 23 -bufsize:v:0 2250k -maxrate:v 2500k \
    -g:v 100000 -keyint_min:v 50000 -force_key_frames:v "expr:gte(t,n_forced*2)" \
    -x264opts no-open-gop=1 \
    -bf 2 -b_strategy 2 -refs 1 \
    -rc-lookahead 24 \
    -export_side_data prft \
    -field_order progressive -colorspace bt709 -color_primaries bt709 -color_trc bt709 -color_range tv \
    -pix_fmt yuv420p \
  -f mp4 \
    -frag_duration "$(( 1*1000*1000 ))" \
    -min_frag_duration "$(( 1*1000*1000 ))" \
    -write_prft wallclock \
    -use_editlist 0 \
    -movflags "+cmaf+dash+delay_moov+skip_sidx+skip_trailer+frag_custom" \
    \
    -method POST \
    -multiple_requests 1 \
    -chunked_post 1 \
    -send_expect_100 1 \
    -headers "DASH-IF-Ingest: 1.1" \
    -headers "Host: localhost:8080" \
    -content_type "" \
    -icy 0 \
    -rw_timeout "$(( 200*1000*1000 ))" \
    -reconnect 1 \
    -reconnect_at_eof 1 \
    -reconnect_on_network_error 1 \
    -reconnect_on_http_error 4xx,5xx \
    -reconnect_delay_max 2 \
    "http://$INGEST_HOST/cmaf/example.str/Switching(video)/Streams(video-720p.cmfv)" \
  \
  -map [v360p] \
  -c:v libx264 \
    -preset:v veryfast \
    -tune zerolatency \
    -profile:v main \
    -crf:v 23 -bufsize:v:0 2250k -maxrate:v 2500k \
    -g:v 100000 -keyint_min:v 50000 -force_key_frames:v "expr:gte(t,n_forced*2)" \
    -x264opts no-open-gop=1 \
    -bf 2 -b_strategy 2 -refs 1 \
    -rc-lookahead 24 \
    -export_side_data prft \
    -field_order progressive -colorspace bt709 -color_primaries bt709 -color_trc bt709 -color_range tv \
    -pix_fmt yuv420p \
  -f mp4 \
    -frag_duration "$(( 1*1000*1000 ))" \
    -min_frag_duration "$(( 1*1000*1000 ))" \
    -write_prft wallclock \
    -use_editlist 0 \
    -movflags "+cmaf+dash+delay_moov+skip_sidx+skip_trailer+frag_custom" \
    \
    -method POST \
    -multiple_requests 1 \
    -chunked_post 1 \
    -send_expect_100 1 \
    -headers "DASH-IF-Ingest: 1.1" \
    -headers "Host: localhost:8080" \
    -content_type "" \
    -icy 0 \
    -rw_timeout "$(( 200*1000*1000 ))" \
    -reconnect 1 \
    -reconnect_at_eof 1 \
    -reconnect_on_network_error 1 \
    -reconnect_on_http_error 4xx,5xx \
    -reconnect_delay_max 2 \
    "http://$INGEST_HOST/cmaf/example.str/Switching(video)/Streams(video-360p.cmfv)" \
  \
  -map 1:a \
  -c:a aac \
    -b:a 64k \
  -f mp4 \
    -frag_duration "$(( 1*1000*1000 ))" \
    -min_frag_duration "$(( 1*1000*1000 ))" \
    -write_prft wallclock \
    -use_editlist 0 \
    -movflags "+cmaf+dash+delay_moov+skip_sidx+skip_trailer+frag_custom" \
    \
    -method POST \
    -multiple_requests 1 \
    -chunked_post 1 \
    -send_expect_100 1 \
    -headers "DASH-IF-Ingest: 1.1" \
    -headers "Host: localhost:8080" \
    -content_type "" \
    -icy 0 \
    -rw_timeout "$(( 200*1000*1000 ))" \
    -reconnect 1 \
    -reconnect_at_eof 1 \
    -reconnect_on_network_error 1 \
    -reconnect_on_http_error 4xx,5xx \
    -reconnect_delay_max 2 \
    "http://$INGEST_HOST/cmaf/example.str/Switching(audio)/Streams(audio-64k.cmfa)"
